### ISSUE TITLE
engine.cfg is missing

### ISSUE THREAD

**Issue by kifhan** [e9aru/ld39-power-necromancell#1]
Could you tell me how to open the project on godot?
Do you open it with cmd?

**Comment by kifhan** [comment]
Oh.. or could you tell me what version of godot do you use?

**Comment by kifhan** [comment]
ah, it seems like you using v3.0 alpha.
I'd build v3.0 from source and it works fine. Great job dude.

**Comment by e9aru** [comment]
Thanks man, I'm glad you liked it ^^
That is right, it's v3
